# Generated by Django 5.0.1 on 2024-01-04 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.ImageField(default='path/to/default/image.png', upload_to='user_profile_images/'),
        ),
    ]
